# Generated by Django 4.2 on 2025-03-14 02:17

import Enseignant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enseignant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[Enseignant.models.verif_username]),
        ),
    ]
