# Generated by Django 4.2 on 2025-03-14 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=20)),
                ('categorie', models.CharField(choices=[('Web', 'Web'), ('Mobile', 'Mobile'), ('Bi ', 'Bi')], max_length=20)),
                ('date_publication', models.DateTimeField()),
                ('tuteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cour',
            },
        ),
    ]
